# Generated by Django 5.1.2 on 2024-10-26 15:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_video_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to=core.models.random_filename, verbose_name='Thumbnail'),
        ),
    ]
